

require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/migrate/20221117075359_create_active_storage_tables.active_storage.rb'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 110

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/MethodParameterName:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/EndOfLine:
   Enabled: False
